/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + DB reachability */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in (sets `sid` cookie) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own profile (display name, email) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change own password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin) */
        get: operations["listUsers"];
        put?: never;
        /** Create user (admin) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive user (admin) */
        delete: operations["archiveUser"];
        options?: never;
        head?: never;
        /** Update user (admin) */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore archived user (admin) */
        post: operations["restoreUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a user's password (admin) */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups (admin) */
        get: operations["listGroups"];
        put?: never;
        /** Create group (admin) */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive group (admin) */
        delete: operations["archiveGroup"];
        options?: never;
        head?: never;
        /** Update group (admin) */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/api/v1/admin/groups/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore archived group (admin) */
        post: operations["restoreGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group members (admin) */
        get: operations["listGroupMembers"];
        put?: never;
        /** Add user to group (admin) */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/groups/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove user from group (admin) */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: operations["listCategories"];
        put?: never;
        /** Create category (admin) */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive category (admin) */
        delete: operations["archiveCategory"];
        options?: never;
        head?: never;
        /** Update category (admin) */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/api/v1/categories/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore category (admin) */
        post: operations["restoreCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/priorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List priorities */
        get: operations["listPriorities"];
        put?: never;
        /** Create priority (admin) */
        post: operations["createPriority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/priorities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive priority (admin) */
        delete: operations["archivePriority"];
        options?: never;
        head?: never;
        /** Update priority (admin) */
        patch: operations["updatePriority"];
        trace?: never;
    };
    "/api/v1/priorities/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore priority (admin) */
        post: operations["restorePriority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible notes */
        get: operations["listNotes"];
        put?: never;
        /** Create note */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get note (≥view) */
        get: operations["getNote"];
        put?: never;
        post?: never;
        /** Archive note (owner) */
        delete: operations["archiveNote"];
        options?: never;
        head?: never;
        /** Update note (≥edit) */
        patch: operations["updateNote"];
        trace?: never;
    };
    "/api/v1/notes/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore note (owner) */
        post: operations["restoreNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible todos */
        get: operations["listTodos"];
        put?: never;
        /** Create todo */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get todo (≥view) */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /** Archive todo (owner) */
        delete: operations["archiveTodo"];
        options?: never;
        head?: never;
        /** Update todo (≥edit) */
        patch: operations["updateTodo"];
        trace?: never;
    };
    "/api/v1/todos/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle done (≥edit) */
        post: operations["toggleTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore todo (owner) */
        post: operations["restoreTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expanded occurrences in a range (RRULE-aware, EXDATEs applied) */
        get: operations["getCalendarRange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible calendar items (base rows, not expanded) */
        get: operations["listCalendarItems"];
        put?: never;
        /** Create calendar item */
        post: operations["createCalendarItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get calendar item (≥view) */
        get: operations["getCalendarItem"];
        put?: never;
        post?: never;
        /** Archive calendar item (owner) */
        delete: operations["archiveCalendarItem"];
        options?: never;
        head?: never;
        /** Update calendar item (≥edit; `exdatesUTC` replaces the EXDATE list) */
        patch: operations["updateCalendarItem"];
        trace?: never;
    };
    "/api/v1/calendar/items/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore calendar item (owner) */
        post: operations["restoreCalendarItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags */
        get: operations["listTags"];
        put?: never;
        /** Create tag (any user) */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive tag (admin) */
        delete: operations["archiveTag"];
        options?: never;
        head?: never;
        /** Update tag (admin) */
        patch: operations["updateTag"];
        trace?: never;
    };
    "/api/v1/tags/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore tag (admin) */
        post: operations["restoreTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach tag to item (≥edit) */
        post: operations["attachTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach tag from item (≥edit) */
        delete: operations["detachTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search visible items (link picker) */
        get: operations["searchItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get base item with the caller's access level */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Linked items (bidirectional, ≥view) */
        get: operations["listLinks"];
        put?: never;
        /** Link two items (≥edit on source, ≥view on target) */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive link (≥edit on either endpoint) */
        delete: operations["deleteLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todo-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own todo templates */
        get: operations["listTemplates"];
        put?: never;
        /** Create template */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todo-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get template with items */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        /** Archive template */
        delete: operations["archiveTemplate"];
        options?: never;
        head?: never;
        /** Update template */
        patch: operations["updateTemplate"];
        trace?: never;
    };
    "/api/v1/todo-templates/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore template */
        post: operations["restoreTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todo-templates/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add template item */
        post: operations["addTemplateItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todo-templates/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive template item */
        delete: operations["archiveTemplateItem"];
        options?: never;
        head?: never;
        /** Update template item */
        patch: operations["updateTemplateItem"];
        trace?: never;
    };
    "/api/v1/todo-templates/{id}/instantiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create todos from the template (due = baseDate + relativeDueDays) */
        post: operations["instantiateTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directory/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active users (share-target picker) */
        get: operations["listDirectoryUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directory/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active groups (share-target picker) */
        get: operations["listDirectoryGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shares on an item (owner) */
        get: operations["listShares"];
        put?: never;
        /** Share item with a user or group (owner) */
        post: operations["createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove share (owner) */
        delete: operations["deleteShare"];
        options?: never;
        head?: never;
        /** Change share level (owner) */
        patch: operations["updateShare"];
        trace?: never;
    };
    "/api/v1/items/{id}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reminders on an item (owner sees all, others their own) */
        get: operations["listReminders"];
        put?: never;
        /** Create reminder (absolute time, or minutes before each calendar occurrence) */
        post: operations["createReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive reminder (creator or item owner) */
        delete: operations["deleteReminder"];
        options?: never;
        head?: never;
        /** Update reminder (creator or item owner) */
        patch: operations["updateReminder"];
        trace?: never;
    };
    "/api/v1/reminders/{id}/dispatches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dispatch log (last 50) */
        get: operations["listReminderDispatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SMTP config (admin; password never returned) */
        get: operations["getSmtpSettings"];
        /** Save SMTP config (admin; omit `password` to keep stored one) */
        put: operations["putSmtpSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test email (admin) */
        post: operations["testSmtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Webhook config (admin; secret never returned) */
        get: operations["getWebhookSettings"];
        /** Save webhook config (admin; omit `secret` to keep stored one) */
        put: operations["putWebhookSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/webhook/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a signed test POST to the webhook (admin) */
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        User: {
            id: number;
            username: string;
            displayName?: string | null;
            email?: string | null;
            isAdmin: boolean;
        };
        AdminUser: components["schemas"]["User"] & {
            /** Format: date-time */
            lastLoginAtUTC?: string | null;
            /** Format: date-time */
            createdAtUTC?: string | null;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        Group: {
            id: number;
            name: string;
            description?: string | null;
            /** Format: date-time */
            createdAtUTC?: string | null;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        GroupMember: {
            id: number;
            userId: number;
            username: string;
            displayName?: string | null;
        };
        Category: {
            id: number;
            name: string;
            color?: string | null;
            sortOrder?: number;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        Priority: {
            id: number;
            name: string;
            color?: string | null;
            weight?: number;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        Tag: {
            id: number;
            name: string;
            color?: string | null;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        ItemBase: {
            id: number;
            title: string;
            tagIds?: number[];
            ownerId: number;
            categoryId?: number | null;
            priorityId?: number | null;
            /** Format: date-time */
            createdAtUTC?: string;
            /** Format: date-time */
            updatedAtUTC?: string;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        Note: components["schemas"]["ItemBase"] & {
            bodyMd?: string | null;
            pinned?: boolean;
        };
        Todo: components["schemas"]["ItemBase"] & {
            done?: boolean;
            /** Format: date-time */
            doneAtUTC?: string | null;
            /** Format: date-time */
            dueAtUTC?: string | null;
            notesMd?: string | null;
        };
        CalendarItem: components["schemas"]["ItemBase"] & {
            /** Format: date-time */
            startAtUTC?: string;
            /** Format: date-time */
            endAtUTC?: string | null;
            allDay?: boolean;
            location?: string | null;
            descriptionMd?: string | null;
            rrule?: string | null;
            timezone?: string | null;
            exdatesUTC?: string[];
        };
        Occurrence: {
            itemId: number;
            title: string;
            /** Format: date-time */
            occurrenceStartUTC: string;
            /** Format: date-time */
            occurrenceEndUTC?: string | null;
            allDay?: boolean;
            recurring: boolean;
            location?: string | null;
            ownerId?: number;
            categoryId?: number | null;
            priorityId?: number | null;
        };
        ItemRef: {
            id: number;
            /** @enum {string} */
            itemType: "note" | "todo" | "calendar";
            title: string;
        };
        BaseItem: components["schemas"]["ItemRef"] & {
            ownerId?: number;
            categoryId?: number | null;
            priorityId?: number | null;
            /** @enum {string} */
            access: "owner" | "edit" | "view";
            /** Format: date-time */
            createdAtUTC?: string;
            /** Format: date-time */
            updatedAtUTC?: string;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        Link: {
            linkId: number;
            linkType?: string | null;
            item: components["schemas"]["ItemRef"];
        };
        Template: {
            id: number;
            name: string;
            description?: string | null;
            ownerId: number;
            /** Format: date-time */
            createdAtUTC?: string;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        TemplateItem: {
            id: number;
            templateId: number;
            title: string;
            categoryId?: number | null;
            priorityId?: number | null;
            relativeDueDays?: number | null;
            sortOrder?: number;
        };
        TemplateWithItems: components["schemas"]["Template"] & {
            items: components["schemas"]["TemplateItem"][];
        };
        DirectoryUser: {
            id: number;
            username: string;
            displayName?: string | null;
        };
        DirectoryGroup: {
            id: number;
            name: string;
        };
        Share: {
            id: number;
            /** @enum {string} */
            level: "view" | "edit";
            grantee: {
                /** @enum {string} */
                type: "user" | "group";
                id: number;
                name: string;
            };
        };
        Reminder: {
            id: number;
            itemId: number;
            createdBy?: number;
            recipientUserId?: number | null;
            /** Format: date-time */
            remindAtUTC?: string | null;
            offsetMinutes?: number | null;
            channels: ("email" | "webhook")[];
            enabled: boolean;
            /** Format: date-time */
            nextFireAtUTC?: string | null;
            /** Format: date-time */
            archivedAtUTC?: string | null;
        };
        Dispatch: {
            id: number;
            /** Format: date-time */
            occurrenceAtUTC: string;
            /** @enum {string} */
            channel: "email" | "webhook";
            /** @enum {string} */
            status: "sent" | "failed";
            attempt: number;
            error?: string | null;
            /** Format: date-time */
            dispatchedAtUTC?: string;
        };
        SmtpSettings: {
            host?: string | null;
            port?: number | null;
            user?: string | null;
            from?: string | null;
            /** @enum {string} */
            tls: "none" | "starttls" | "tls";
            hasPassword: boolean;
        };
        WebhookSettings: {
            url?: string | null;
            enabled: boolean;
            hasSecret: boolean;
        };
    };
    responses: {
        /** @description OK */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok?: boolean;
                };
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict (duplicate among active rows) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: number;
        IncludeArchived: "true" | "false";
    };
    requestBodies: {
        CategoryBody: {
            content: {
                "application/json": {
                    name?: string;
                    color?: string | null;
                    sortOrder?: number;
                };
            };
        };
        PriorityBody: {
            content: {
                "application/json": {
                    name?: string;
                    color?: string | null;
                    weight?: number;
                };
            };
        };
        NoteBody: {
            content: {
                "application/json": {
                    title?: string;
                    bodyMd?: string | null;
                    pinned?: boolean;
                    categoryId?: number | null;
                    priorityId?: number | null;
                };
            };
        };
        TodoBody: {
            content: {
                "application/json": {
                    title?: string;
                    done?: boolean;
                    /** Format: date-time */
                    dueAtUTC?: string | null;
                    notesMd?: string | null;
                    categoryId?: number | null;
                    priorityId?: number | null;
                };
            };
        };
        CalendarBody: {
            content: {
                "application/json": {
                    title?: string;
                    /** Format: date-time */
                    startAtUTC?: string;
                    /** Format: date-time */
                    endAtUTC?: string | null;
                    allDay?: boolean;
                    location?: string | null;
                    descriptionMd?: string | null;
                    /** @description RFC 5545 RRULE body, e.g. FREQ=WEEKLY;BYDAY=MO */
                    rrule?: string | null;
                    /** @description IANA zone the rule was authored in (DST-correct expansion) */
                    timezone?: string | null;
                    exdatesUTC?: string[];
                    categoryId?: number | null;
                    priorityId?: number | null;
                };
            };
        };
        TemplateItemBody: {
            content: {
                "application/json": {
                    title?: string;
                    categoryId?: number | null;
                    priorityId?: number | null;
                    /** @description Due = baseDate + N days; null = no due date */
                    relativeDueDays?: number | null;
                    sortOrder?: number;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** @enum {string} */
                        db: "ok" | "down";
                        /** Format: date-time */
                        time_UTC: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string | null;
                    email?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    displayName?: string | null;
                    email?: string | null;
                    isAdmin?: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    archiveUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName?: string | null;
                    email?: string | null;
                    isAdmin?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    restoreUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    archiveGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    restoreGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    listGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"][];
                };
            };
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userId: number;
                };
            };
        };
        responses: {
            201: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CategoryBody"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    archiveCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CategoryBody"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    restoreCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    listPriorities: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Priorities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priority"][];
                };
            };
        };
    };
    createPriority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PriorityBody"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priority"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    archivePriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updatePriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PriorityBody"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priority"];
                };
            };
        };
    };
    restorePriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    listNotes: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
                /** @description Search title/body */
                q?: string;
                category?: number;
                tag?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"][];
                };
            };
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["NoteBody"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["NoteBody"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    restoreNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listTodos: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
                q?: string;
                category?: number;
                priority?: number;
                tag?: number;
                done?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TodoBody"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TodoBody"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
        };
    };
    toggleTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
        };
    };
    restoreTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    getCalendarRange: {
        parameters: {
            query: {
                from: string;
                /** @description Max 400 days after `from` */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Occurrences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Occurrence"][];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    listCalendarItems: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
                q?: string;
                tag?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"][];
                };
            };
        };
    };
    createCalendarItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CalendarBody"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"];
                };
            };
        };
    };
    getCalendarItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveCalendarItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateCalendarItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CalendarBody"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarItem"];
                };
            };
        };
    };
    restoreCalendarItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listTags: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    color?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    archiveTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    color?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
        };
    };
    restoreTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    attachTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tagId: number;
                };
            };
        };
        responses: {
            201: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    detachTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                tagId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    searchItems: {
        parameters: {
            query?: {
                type?: "note" | "todo" | "calendar";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items (max 30) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemRef"][];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Base item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseItem"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listLinks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"][];
                };
            };
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    toItemId: number;
                    linkType?: string | null;
                };
            };
        };
        responses: {
            201: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"][];
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateWithItems"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string | null;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
        };
    };
    restoreTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    addTemplateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TemplateItemBody"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateItem"];
                };
            };
        };
    };
    archiveTemplateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateTemplateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                itemId: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TemplateItemBody"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateItem"];
                };
            };
        };
    };
    instantiateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date-time
                     * @description Defaults to now
                     */
                    baseDateUTC?: string;
                };
            };
        };
        responses: {
            /** @description Created todos */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        createdTodoIds: number[];
                    };
                };
            };
            /** @description Template has no items */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDirectoryUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryUser"][];
                };
            };
        };
    };
    listDirectoryGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryGroup"][];
                };
            };
        };
    };
    listShares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shares */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    granteeType: "user" | "group";
                    granteeId: number;
                    /** @enum {string} */
                    level: "view" | "edit";
                };
            };
        };
        responses: {
            201: components["responses"]["Ok"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    level: "view" | "edit";
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listReminders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"][];
                };
            };
        };
    };
    createReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    remindAtUTC?: string | null;
                    /** @description Calendar items only */
                    offsetMinutes?: number | null;
                    channels: ("email" | "webhook")[];
                    /** @description Defaults to creator */
                    recipientUserId?: number | null;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    deleteReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    updateReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date-time */
                    remindAtUTC?: string | null;
                    offsetMinutes?: number | null;
                    channels?: ("email" | "webhook")[];
                    recipientUserId?: number | null;
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
        };
    };
    listReminderDispatches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispatches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dispatch"][];
                };
            };
        };
    };
    getSmtpSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpSettings"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    putSmtpSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    host: string | null;
                    port: number | null;
                    user?: string | null;
                    /** @description Stored AES-256-GCM encrypted */
                    password?: string | null;
                    from: string | null;
                    /** @enum {string} */
                    tls: "none" | "starttls" | "tls";
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    testSmtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Defaults to caller's email */
                    to?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            422: components["responses"]["Unprocessable"];
            /** @description Send failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWebhookSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSettings"];
                };
            };
        };
    };
    putWebhookSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    url: string | null;
                    enabled: boolean;
                    /** @description HMAC-SHA256 key; signature sent as x-notestodo-signature */
                    secret?: string | null;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            422: components["responses"]["Unprocessable"];
            /** @description Request failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
